spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.66.11:3306/mymall_sms
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.66.11:8848
      config:
        server-addr: 192.168.66.11:8848
  application:
    name: coupon

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

server:
  port: 7000